# -*- coding: utf-8 -*-
"""cohort_week_1_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOOOHbDp-czd4M7RRizGd68b1c2QQqQp
"""

# Part 1 — Data Understanding & Exploration

import pandas as pd

# Read the data from the source using pandas lib

data = pd.read_csv("/content/test_zomato.csv")

data.head()

# Print the shape of the data

print(data.shape)

# Print all columns

print(data.columns)

# Print the data type of each columns

print(data.dtypes)

# Print Count of null values in each column in the data

print(data.isna().sum())

# Identify duplicate records (if any)

duplicated_records = data.duplicated().sum()
print(f"Total duplicate records: {duplicated_records}")

# Displays the rows that are duplicated (if any)

duplicated_rows = data[data.duplicated()]
print(duplicated_rows)

# Checking the current data type of average cost for two column

avg_cost_for_two_dtype = data['Average Cost for two'].dtypes
print(avg_cost_for_two_dtype)

# Displaying the values inside the column

print(data['Average Cost for two'])

# Checking if all the value inside the column is numberic or not and printing only the rows which have non numberic values

is_numeric = data['Average Cost for two'].astype(str).str.isnumeric()
print(data[~is_numeric][['Restaurant Name', 'Average Cost for two']])

# Converting object data type into numberic data type

data['Average Cost for two'] = pd.to_numeric(data['Average Cost for two'], errors="coerce")
print(data['Average Cost for two'].dtypes)

# Statistical analysis

data.describe()

# mean, median and mode of the col 'Average cost for two'

print(data['Average Cost for two'].mean())
print(data['Average Cost for two'].median())
print(data['Average Cost for two'].mode())

# How many unique cities are present in the dataset?

no_of_unique_cities = data['City'].nunique()
print(f"No.of Unique cities: {no_of_unique_cities}")

# Which city has the highest number of restaurants?

city_with_highest_no_of_restaurents = data['City'].value_counts().idxmax()
print(f"City with the highest number of restaurents: {city_with_highest_no_of_restaurents}")

# Which cuisine appears most frequently?

most_freequent_cuisine = data['Cuisines'].value_counts().idxmax()
print(f"Which cuisine appears most freequently: {most_freequent_cuisine}")

# Part 2 - Data Analysis

# Find the average restaurant rating

# Checking the type of the col 'Aggregate rating'
print(data['Aggregate rating'].dtype)

# taking the avg of col 'Aggregate rating'
avg_rating_of_restaurents = data['Aggregate rating'].mean()
print(f"Average rating of restaurents is: {avg_rating_of_restaurents:.2f}")

# Identify the restaurant with the highest number of votes

highest_vote = data['Votes'].idxmax()

restaurant_with_highest_vote = data.loc[highest_vote, 'Restaurant Name']
restaurant_with_highest_vote_value = data.loc[highest_vote, 'Votes']

print(f"Restaurant with highest vote is {restaurant_with_highest_vote} with a vote count of {int(restaurant_with_highest_vote_value)}")

# Find the average cost for two across all restaurants

overall_avg_cost = data['Average Cost for two'].mean()

print(f"The average cost for two across all restaurants is: {overall_avg_cost:.2f}")

# Compare the average ratings of restaurants that:
# a. Have Online Delivery
# b. Do Not Have Online Delivery

delivery_stats = data.groupby('Has Online delivery')['Aggregate rating'].mean()

print(delivery_stats)
print()

# Cleaned up version

filtered_stats = delivery_stats.loc[['Yes', 'No']]
print(filtered_stats)

# Compare the average ratings of restaurants that:
# a. Have Table Booking
# b. Do Not Have Table Booking

booking_stats = data.groupby('Has Table booking')['Aggregate rating'].mean()

print(booking_stats)
print()

# Cleaned up version

filtered_booking_stats = booking_stats.loc[['Yes', 'No']]
print(filtered_booking_stats)

# Identify the top 10 cities with the highest number of restaurants

top_10_cities = data['City'].value_counts().head(10)

print("Top 10 Cities with the highest number of restaurants are:")
print(top_10_cities)

# Part 3 — Data Visualization

# importing required libs for the data visualization

import matplotlib.pyplot as plt
import seaborn as sb

# 1. Bar Chart: Top 10 cities with the highest number of restaurants

plt.figure(figsize=(10, 6))
top_10_cities = data['City'].value_counts().head(10)
sb.barplot(x=top_10_cities.values, y=top_10_cities.index, hue=top_10_cities.index, palette='viridis', legend=False)
plt.title('Top 10 Cities with the Highest Number of Restaurants')
plt.xlabel('Number of Restaurants')
plt.ylabel('City')
plt.show()

# 2. Histogram: Distribution of Aggregate Ratings

plt.figure(figsize=(10, 6))
sb.histplot(data['Aggregate rating'], bins=20, kde=True, color='skyblue')
plt.title('Distribution of Aggregate Ratings')
plt.xlabel('Aggregate Rating')
plt.ylabel('Frequency')
plt.show()

# 3. Bar Chart: Number of restaurants offering Online Delivery (Yes/No)

plt.figure(figsize=(8, 6))
sb.countplot(x='Has Online delivery', data=data, hue='Has Online delivery', palette='pastel', order=['Yes', 'No'], legend=False)
plt.title('Number of Restaurants Offering Online Delivery')
plt.xlabel('Offers Online Delivery')
plt.ylabel('Count of Restaurants')
plt.show()

# 4. Bar Chart: Top 10 most common cuisines

plt.figure(figsize=(10, 6))
top_10_cuisines = data['Cuisines'].value_counts().head(10)
sb.barplot(x=top_10_cuisines.values, y=top_10_cuisines.index, hue=top_10_cuisines.index, palette='magma', legend=True)
plt.title('Top 10 Most Common Cuisines')
plt.xlabel('Number of Restaurants')
plt.ylabel('Cuisine')
plt.show()

# 5. Line Chart: Average restaurant rating by Price Range

plt.figure(figsize=(10, 6))
avg_rating_price = data.groupby('Price range')['Aggregate rating'].mean().reset_index()
sb.lineplot(x='Price range', y='Aggregate rating', data=avg_rating_price, marker='o', color='red')
plt.title('Average Restaurant Rating by Price Range')
plt.xlabel('Price Range (1-4)')
plt.ylabel('Average Aggregate Rating')
plt.grid(True)
plt.show()